# K-Scale Style Motor Configuration
# Based on K-Scale Labs architecture

robot:
  name: "melvin"
  description: "Single Robstride motor test"

# Motor configurations
motors:
  main_motor:
    type: "robstride"
    can_id: 0x0F  # Motor ID 15 in hex
    bus_id: 0
    
    # Physical limits (MIT protocol)
    limits:
      position_min: -12.5      # radians
      position_max: 12.5       # radians
      velocity_min: -45.0      # rad/s
      velocity_max: 45.0       # rad/s
      torque_min: -18.0        # Nm
      torque_max: 18.0         # Nm
      kp_min: 0.0
      kp_max: 500.0
      kd_min: 0.0
      kd_max: 5.0
    
    # Default control parameters
    control:
      default_kp: 30.0
      default_kd: 1.5
      default_velocity: 0.0
      default_torque: 0.0
    
    # Communication settings
    communication:
      port: null  # auto-detect
      baudrate: 115200
      timeout: 0.5
      protocol: "L91"  # SLCAN protocol variant

# Limb definitions (K-Scale style)
limbs:
  test_limb:
    motors: ["main_motor"]
    start_can_id: 0x0F  # Motor ID 15
    dof: 1
    bus_id: 0

