inbox_dir: "data/inbox"
processed_dir: "data/processed"
failed_dir: "data/failed"

poll_seconds: 3
snapshot_every_seconds: 60
metrics_every_seconds: 10
max_files_per_tick: 4

# Turn on when Patch Pack E lands; safe no-ops for now
enable_decay: false
enable_srs: false

# Where to write rolling metrics
metrics_csv: "logs/continuous_learning_metrics.csv"

