# Evolution Mode Configuration
# Patch Pack E - v0.10.0
# Adaptive learning with forgetting, reinforcement, and deep reasoning

# ============================================================================
# PHASE 1: Multi-Hop Reasoning Engine
# ============================================================================

multihop:
  enabled: true
  max_hops: 3                # Maximum reasoning depth (1, 2, or 3 hops)
  beam_width: 5              # Number of paths to explore in parallel
  length_penalty: 0.9        # Penalty for longer paths (prefer shorter)
  
  # Relation type priors (weight multipliers)
  # Higher values = more trust in that relation type
  relation_priors:
    ARE: 1.0
    IS_A: 1.0
    DRINK: 0.9
    NEED: 0.9
    HAVE: 0.8
    PART_OF: 0.8
    PRODUCES: 0.7
    CAUSES: 0.7
    USES: 0.6
    SIMILAR_TO: 0.5
    ASSOC: 0.5

# ============================================================================
# PHASE 2: Edge Decay (Ebbinghaus Forgetting)
# ============================================================================

decay:
  enabled: true              # ✓ ENABLED in Phase 2
  half_life_days: 7.0        # Time for weight to decay 50%
  floor: 0.05                # Minimum weight (never decay below)
  max: 4.0                   # Maximum weight (cap reinforcement)
  check_interval_hours: 24   # How often to run decay pass
  decay_function: exponential # Ebbinghaus curve

# ============================================================================
# PHASE 3: Spaced Repetition System (SRS)
# ============================================================================

srs:
  enabled: false             # TODO: Enable in Phase 3
  algorithm: SM2             # SM2 or simplified
  base_interval_days: 1.0    # First repetition after 1 day
  ease_factor_min: 1.3       # Minimum ease multiplier
  ease_factor_max: 2.5       # Maximum ease multiplier
  rehearsal_threshold: 0.5   # Trigger if weight < threshold
  auto_generate_lessons: true # Create rehearsal .tch files

# ============================================================================
# PHASE 4: Path Verification
# ============================================================================

path_verification:
  enabled: false             # TODO: Enable in Phase 5
  require_path: true         # FAIL if path doesn't match expected
  partial_credit: true       # Give 50% for right answer, wrong path
  max_path_length: 5         # Reject paths longer than this
  verify_intermediate: true  # Check each hop, not just final answer

# ============================================================================
# PHASE 5: Teaching Format V2
# ============================================================================

teaching_v2:
  enable_alias: false        # TODO: Enable in Phase 4
  enable_derive: false       # TODO: Enable in Phase 4
  enable_neg: false          # TODO: Enable in Phase 4
  merge_alias_embeddings: true
  derive_creates_virtual_edges: true
  neg_weight: -0.5           # Negative edge weight

# ============================================================================
# Integration with Continuous Learning
# ============================================================================

continuous_learning_hooks:
  call_multihop_for_queries: true  # Use multi-hop in verify
  call_decay_every_tick: false     # TODO: Enable in Phase 2
  call_srs_every_tick: false       # TODO: Enable in Phase 3
  log_reasoning_paths: true        # Log paths to metrics CSV

# ============================================================================
# Metrics & Monitoring
# ============================================================================

metrics:
  log_multihop_stats: true
  log_decay_stats: false     # TODO: Enable in Phase 2
  log_srs_stats: false       # TODO: Enable in Phase 3
  log_path_correctness: false # TODO: Enable in Phase 5
  
  # Additional columns for continuous_learning_metrics.csv
  additional_columns:
    - hop_count_avg
    - path_score_avg
    # - decay_edges_affected    # TODO: Phase 2
    # - srs_rehearsals_due      # TODO: Phase 3

