# Evolution Mode Configuration
# Patch Pack E - v0.10.0
# Adaptive learning with forgetting, reinforcement, and deep reasoning

# ============================================================================
# PHASE 1: Multi-Hop Reasoning Engine
# ============================================================================

multihop:
  enabled: true
  max_hops: 3                # Maximum reasoning depth (1, 2, or 3 hops)
  beam_width: 5              # Number of paths to explore in parallel
  length_penalty: 0.9        # Penalty for longer paths (prefer shorter)
  
  # Relation type priors (weight multipliers)
  # Higher values = more trust in that relation type
  relation_priors:
    ARE: 1.0
    IS_A: 1.0
    DRINK: 0.9
    NEED: 0.9
    HAVE: 0.8
    PART_OF: 0.8
    PRODUCES: 0.7
    CAUSES: 0.7
    USES: 0.6
    SIMILAR_TO: 0.5
    ASSOC: 0.5

# ============================================================================
# PHASE 2: Edge Decay (Ebbinghaus Forgetting)
# ============================================================================

decay:
  enabled: true              # ✓ ENABLED in Phase 2
  half_life_days: 7.0        # Time for weight to decay 50%
  floor: 0.05                # Minimum weight (never decay below)
  max: 4.0                   # Maximum weight (cap reinforcement)
  check_interval_hours: 24   # How often to run decay pass
  decay_function: exponential # Ebbinghaus curve

# ============================================================================
# PHASE 3: Spaced Repetition System (SRS)
# ============================================================================

srs:
  enabled: true              # ✓ ENABLED in Phase 3
  algorithm: SM2             # SM-2 spaced repetition
  daily_limit: 200           # Max reviews per day
  min_interval_days: 1.0     # First review after 1 day
  max_interval_days: 60.0    # Maximum interval (2 months)
  ease_start: 2.5            # Initial ease factor
  ease_floor: 1.3            # Minimum ease
  ease_step_good: 0.15       # Ease increase on GOOD
  ease_step_hard: -0.2       # Ease decrease on HARD
  lapse_factor: 0.5          # Interval multiplier on FAIL
  streak_reset_on_lapse: true # Reset streak on FAIL
  auto_generate_lessons: true # Create rehearsal .tch files
  rehearsal_dir: "data/inbox" # Where to place rehearsals

# ============================================================================
# PHASE 4: Path Verification
# ============================================================================

path_verification:
  enabled: false             # TODO: Enable in Phase 5
  require_path: true         # FAIL if path doesn't match expected
  partial_credit: true       # Give 50% for right answer, wrong path
  max_path_length: 5         # Reject paths longer than this
  verify_intermediate: true  # Check each hop, not just final answer

# ============================================================================
# PHASE 5: Teaching Format V2
# ============================================================================

teaching_v2:
  enable_alias: false        # TODO: Enable in Phase 4
  enable_derive: false       # TODO: Enable in Phase 4
  enable_neg: false          # TODO: Enable in Phase 4
  merge_alias_embeddings: true
  derive_creates_virtual_edges: true
  neg_weight: -0.5           # Negative edge weight

# ============================================================================
# Integration with Continuous Learning
# ============================================================================

continuous_learning_hooks:
  call_multihop_for_queries: true  # Use multi-hop in verify
  call_decay_every_tick: true      # ✓ ENABLED (Phase 2)
  call_srs_every_tick: true        # ✓ ENABLED (Phase 3)
  log_reasoning_paths: true        # Log paths to metrics CSV
  daily_limit_per_tick: 10         # Max SRS reviews per tick

# ============================================================================
# Probes (Multi-hop query monitoring)
# ============================================================================

probes:
  enabled: true
  multihop_queries_file: "data/probes/multihop_5.txt"
  run_every_ticks: 10              # Run probe every 10 ticks
  min_success_rate: 0.6            # Target: 60%+ probe success

# ============================================================================
# Metrics & Monitoring
# ============================================================================

metrics:
  log_multihop_stats: true
  log_decay_stats: true      # ✓ ENABLED (Phase 2)
  log_srs_stats: true        # ✓ ENABLED (Phase 3)
  log_path_correctness: false # TODO: Enable in Phase 5
  
  # Additional columns for continuous_learning_metrics.csv
  additional_columns:
    - multihop_probe_success   # % of probe queries answered via multi-hop
    - multihop_avg_path_len    # Average path length in successful queries
    - decay_events             # Number of edges decayed this tick
    - avg_edge_weight          # Average weight across all edges
    - pct_edges_below_0_1      # % of edges near floor (weak knowledge)
    - srs_due                  # Items due for review
    - srs_reviewed             # Items reviewed this tick
    - srs_pass_rate            # Pass rate (EASY+GOOD+HARD)/total
    - srs_avg_interval         # Average review interval (days)
    - srs_avg_ease             # Average ease factor

